#!/bin/bash

function die() {
    echo "$*" 1>&2
    exit 1
}


MAINCLASS="org.json4s.examples.SerBench"
shift
if test x"$MAINCLASS" = x; then
    die 'This "start" script requires a main class name as the first argument, because a mainClass was not specified in SBT and not autodetected by SBT (usually means you have zero, or more than one, main classes).  You could specify in your SBT build: mainClass in Compile := Some("Whatever")'
fi



JAVA_OPTS="$JAVA_OPTS -agentpath:/Applications/YourKit.app/bin/mac/libyjpagent.jnilib=onexit=snapshot,tracing" examples/target/start $MAINCLASS

